CREATE TABLE Customer (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  last_name VARCHAR(60) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  zip_Code VARCHAR(10) NOT NULL,
  street VARCHAR(255) NOT NULL,
  income DECIMAL(19, 2)
);