CREATE TABLE Cliente (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  lastName VARCHAR(60) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  address_zipCode VARCHAR(10) NOT NULL,
  address_street VARCHAR(255) NOT NULL,
  income DECIMAL(19, 2)
);